name: linters

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/linters.yml"
      - ".flake8"
      - ".isort.cfg"
      - ".pylintrc"
      - "asymmetric/**/*.py"

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install Poetry
        run: make get-poetry

      - name: Add system path to Poetry
        run: echo $HOME/.poetry/bin >> $GITHUB_PATH

      - name: Set up Poetry cache
        uses: actions/cache@v2
        id: poetry-cache
        with:
          key: ${{ hashFiles('**/poetry.lock') }}
          path: .venv

      - name: Install dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Lint with Black
        run: make black

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install Poetry
        run: make get-poetry

      - name: Add system path to Poetry
        run: echo $HOME/.poetry/bin >> $GITHUB_PATH

      - name: Set up Poetry cache
        uses: actions/cache@v2
        id: poetry-cache
        with:
          key: ${{ hashFiles('**/poetry.lock') }}
          path: .venv

      - name: Install dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Lint with Flake8
        run: make flake8

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install Poetry
        run: make get-poetry

      - name: Add system path to Poetry
        run: echo $HOME/.poetry/bin >> $GITHUB_PATH

      - name: Set up Poetry cache
        uses: actions/cache@v2
        id: poetry-cache
        with:
          key: ${{ hashFiles('**/poetry.lock') }}
          path: .venv

      - name: Install dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Lint with Isort
        run: make isort

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install Poetry
        run: make get-poetry

      - name: Add system path to Poetry
        run: echo $HOME/.poetry/bin >> $GITHUB_PATH

      - name: Set up Poetry cache
        uses: actions/cache@v2
        id: poetry-cache
        with:
          key: ${{ hashFiles('**/poetry.lock') }}
          path: .venv

      - name: Install dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Lint with Mypy
        run: make mypy

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install Poetry
        run: make get-poetry

      - name: Add system path to Poetry
        run: echo $HOME/.poetry/bin >> $GITHUB_PATH

      - name: Set up Poetry cache
        uses: actions/cache@v2
        id: poetry-cache
        with:
          key: ${{ hashFiles('**/poetry.lock') }}
          path: .venv

      - name: Install dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Lint with Pylint
        run: make pylint
