name: release

on:
  push:
    branches:
      - stable

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install Poetry
        run: make get-poetry

      - name: Add system path to Poetry
        run: echo $HOME/.poetry/bin >> $GITHUB_PATH

      - name: Set up Poetry cache
        uses: actions/cache@v2
        id: poetry-cache
        with:
          key: ${{ hashFiles('**/poetry.lock') }}
          path: .venv

      - name: Install dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Build the package
        run: poetry build

      - name: Publish the package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
